name: Deploy Backend (SAM)

on:
  push:
    branches: ["main"]
    paths:
      - 'backend/**'
      - 'infra/**'
      - '.github/workflows/backend.yml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: List backend files
        run: |
          ls -la backend
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/common_layer/requirements.txt ]; then pip install -r backend/common_layer/requirements.txt; fi

  deploy-backend:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: SAM Build
        run: sam build
        working-directory: ./infra
        env:
          SAM_CLI_TELEMETRY: 0

      - name: SAM Deploy
        run: sam deploy --stack-name portfolio-sam-app --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM
        working-directory: ./infra
        env:
          SAM_CLI_TELEMETRY: 0
